### ISSUE TITLE
Syntax change request: Use Blocks vs Lambdas

### ISSUE THREAD

**Issue by baweaver** [jonatas/fast#10]
For the Rewriter and `replace` syntaxes, you're using lambda functions:

```ruby
query = '(def $_ ... (send (send nil $_) \1))'

Fast.replace ast, query, -> (node, captures) {
  attribute, object = captures

  replace(
    node.location.expression,
    "delegate :#{attribute}, to: :#{object}"
  )
}
```
Would it be possible to use Ruby block functions instead? The new syntax would look like this:

```ruby
query = '(def $_ ... (send (send nil $_) \1))'

# do ... end block
Fast.replace ast, query do |node, captures|
  attribute, object = captures

  replace(
    node.location.expression,
    "delegate :#{attribute}, to: :#{object}"
  )
end

# { ... } block
Fast.replace(ast, query) { |node, captures|
  attribute, object = captures

  replace(
    node.location.expression,
    "delegate :#{attribute}, to: :#{object}"
  )
}
```

This syntax is a bit cleaner, and Ruby optimizes for it under the hood.

The necessary change would be prepending an ampersand on the function in methods like `replace`:

```ruby
# Old
def replace(ast, search, replacement)

# New
def replace(ast, search, &replacement)
```

As with my other issues, I would be willing to do this work for you and take care of the specs / documentation afterwards.

**Comment by jonatas** [comment]
Good suggestion @baweaver! I agree with the change, feel free to open a PR for it.
