### ISSUE TITLE
Runtime dependency on pry?

### ISSUE THREAD

**Issue by zverok** [jonatas/fast#22]
Hey!

While planning to release a gem based on (awesome :heart_eyes:) `ffast`, I noticed it pulls `pry` as its **runtime** dependency. Is this intended? I don't see any usage of `pry` in `lib/` so it seems it should be rather development depenedency?..

**Comment by jonatas** [comment]
Hey @zverok ! glad to hear that! I'm going to remove it from runtime because it's only useful in the CLI with `--pry` to jump into debugging session. 

Let me know when you publish the gem ❤️

**Comment by jonatas** [comment]
Done! https://github.com/jonatas/fast/commit/85fdbc636ad53549266df4d4c25ff59adc14dcca

Also released a new version to make it easy :)

**Comment by zverok** [comment]
Thanks! :+1: 
The gem is already released: https://github.com/zverok/the_schema_is
I'll update to the newest `fast` in the next version :)

**Comment by jonatas** [comment]
Very cool @zverok! I personally liked the gem idea and the tooling to make it easy to adopt!

Also, the idea of having the `ffast` method in the AST node is great! I'm adding something similar on #21.
